MvcKnolegeStation/Controllers/PictureWallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using ToolFunction;
using MvcKnolegeStation.Models;

namespace MvcKnolegeStation.Controllers
{
    public class PictureWallController : Controller
    {
        //
        // GET: /PictureWall/

        public ActionResult Index()
        {
            string _strSql = "select * from picturewall";
            DataTable _dtPictures = CommonFunction.OraExecuteBySQL(_strSql, new Dictionary<string, string>(), "Pictures");
            PublicProperity.m_dtKnoledges = _dtPictures;
            List<DataRow> _listPicture = new List<DataRow>();
            foreach (DataRow item in _dtPictures.Rows)
            {
                _listPicture.Add(item);
            }
            ViewBag.Pictures = _listPicture;
            Session.Add("Pictures", _listPicture);
            return View();
        }

        //
        // GET: /PictureWall/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /PictureWall/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PictureWall/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PictureWall/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /PictureWall/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PictureWall/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /PictureWall/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcKnolegeStation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Bootstrap Core CSS -->
    <link href="../../Content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="../../Content/landing-page.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="../../Content/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic"
        rel="stylesheet" type="text/css">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              @using (Html.BeginForm("Search", "Knoledge"))
              {
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">@Html.ActionLink("Home", "Index", "Home")</a>
                    </li>
                    <li>
                        <a href="#services">@Html.ActionLink("照片墙", "Index", "PictureWall")</a>
                    </li>
                    <li>
                        <a href="#contact">@Html.ActionLink("上传统计", "About", "Home")</a>
                    </li>
                    <li>
                        <a href="#contact">@Html.ActionLink("所有条目", "Index", "Knoledge")</a>
                    </li>
                     <li>
                       <input name="search" type='text'  />
                    </li>
                     <li>
                       <input  type="submit" value="Search" />
                    </li>
                </ul>
              }
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>
                            Knowledge base</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @RenderSection("favoritem", required: false)
    @RenderSection("newitem", required: false)
    <div class="container">
        @RenderBody()
    </div>
    <a name="contact"></a>
    <div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2>
                        Knoledge Base </h2>
                </div>
                
            </div>
        </div>
        <!-- /.container -->
    </div>
    <!-- /.banner -->
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Favorite Items</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Newest Items</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    <!-- jQuery -->
    <script src="../../Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="../../Scripts/bootstrap.min.js"></script>
</body>
</html>